// Effective context window and usable budget, resolved at hook time.
//
// No imports, no I/O, no network: this is on the hot path. It reads environment
// variables and consults a baked table. Nothing else.
//
// THE DISTINCTION THAT MATTERS. A model's API context window
// (max_input_tokens — 1M on every current frontier model) IS the window Claude
// Code gives its main loop on current frontier models, unless something turns
// it off. Measured 2026-08-10 via /context (CLI 2.1.226), one variable per run:
// default claude-sonnet-5 session reported a 967k window (1M less the
// auto-compact buffer); the same container with CLAUDE_CODE_DISABLE_1M_CONTEXT=1
// reported 200k; claude-opus-5 reported 1m; claude-haiku-4-5 reported 200k.
//
// An earlier measurement (2026-08-05) that showed opus-5 in a 200k window and
// justified an unconditional clamp here was confounded: that environment had
// CLAUDE_CODE_DISABLE_1M_CONTEXT=1 injected by server-managed settings. The
// observation showed the off-switch working, not a universal cap.
//
// A SECOND DISTINCTION, measured 2026-08-10: a model's ceiling is not its
// DEFAULT. Some 1M-capable models run at the base tier unless the 1M variant
// is explicitly selected. Measured per model on this account, headless and
// (for opus-4-6) interactively, same answer on both surfaces:
//   1M by default:   fable-5, sonnet-5, opus-5, opus-4-8  (docs: "always run
//                    with the 1M window" covers Fable 5, Sonnet 5, Opus 4.7+)
//   200k by default: opus-4-6, sonnet-4-6, sonnet-4-5 — 1M exists but is
//                    opt-in (usage credits / [1m] picker variant)
// DEFAULT_1M below encodes that split. A model outside it gets the base tier
// unless its id carries the explicit [1m] suffix.
//
// So the resolution is: explicit config, then what the CLI tells us, then the
// model's DEFAULT window, with the documented off-switches applied:
// CLAUDE_CODE_DISABLE_1M_CONTEXT=1 (docs: "treats Sonnet 5 sessions as having
// a 200K window"), or an LLM gateway (docs: when ANTHROPIC_BASE_URL points at
// a gateway, Claude Code can't verify 1M support and budgets 200K — unless the
// user explicitly selects a [1m] model variant).

// Claude Code's default main-loop window.
const BASE_TIER = 200_000

// The auto-compact buffer is a FLAT reserve, not a fraction of the window.
// Measured 2026-08-10 via /context (CLI 2.1.226): 33k on a 200k window and 33k
// on a 967k sonnet-5 window — the same absolute figure at windows ~5x apart.
// (Opus and Fable sessions report no buffer row at all; reserving 33k for them
// too errs ~3% conservative, the direction this module always errs.)
//
// The USABLE_FRACTION = 0.835 this replaces was exactly 1 - 33000/200000: this
// same flat reserve, read off the base tier on 2026-08-05 and mistaken for a
// proportion. It was right at 200k and nowhere else — at 1M it predicted a
// 165k buffer against a real 33k. Nothing caught it because until issue #3 was
// fixed no window other than 200k could reach usableBudget.
//
// Two env vars this module used to honor were measured inert on 2026-08-10,
// one variable per run, byte-identical /context accounting:
// - CLAUDE_AUTOCOMPACT_PCT_OVERRIDE (unset / 50 / 80): does not move the CLI's
//   compaction threshold, so scaling the budget by it invented a number
//   nothing in the session corresponded to.
// - CLAUDE_CODE_MAX_OUTPUT_TOKENS=48000: not deducted from input-side
//   accounting at all, so subtracting it here understated the budget by
//   exactly its value.
const AUTOCOMPACT_RESERVE = 33_000

// Per-model API context ceilings (max_input_tokens), generated by
// `node scripts/models.mjs` from GET /v1/models on 2026-08-05. Regenerate when
// models ship; do not hand-edit. Hand-writing this table from memory got three
// of twelve rows wrong — sonnet-4-5 is 1M not 200k, and two invented models
// were not in the list at all.
//
// A model absent here falls back to BASE_TIER, which is correct for every model
// at or above the base tier and only overstates for a model with a window
// smaller than 200k. None exist today.
export const MODEL_WINDOWS = {
  'claude-opus-5': 1_000_000,
  'claude-sonnet-5': 1_000_000,
  'claude-fable-5': 1_000_000,
  'claude-opus-4-8': 1_000_000,
  'claude-opus-4-7': 1_000_000,
  'claude-sonnet-4-6': 1_000_000,
  'claude-opus-4-6': 1_000_000,
  'claude-opus-4-5-20251101': 200_000,
  'claude-haiku-4-5-20251001': 200_000,
  'claude-sonnet-4-5-20250929': 1_000_000,
}

// Models that run the 1M window BY DEFAULT — no credits, no [1m] variant, no
// picker step. Membership requires either a live measurement or the docs'
// "always run with the 1M window" list (Fable 5, Sonnet 5, Opus 4.7 and
// later); a ceiling of 1M in MODEL_WINDOWS is deliberately not enough, because
// opus-4-6 / sonnet-4-6 / sonnet-4-5 all have 1M ceilings and all measured
// 200k by default (2026-08-10, CLI 2.1.226). Bare ids; dated variants match by
// prefix, like MODEL_WINDOWS keys.
const DEFAULT_1M = ['claude-fable-5', 'claude-sonnet-5', 'claude-opus-5', 'claude-opus-4-8', 'claude-opus-4-7']

function defaultsToOneM (model) {
  if (!model) return false
  const bare = model.replace(/\[1m\]$/, '')
  return DEFAULT_1M.some(id => bare === id || bare.startsWith(id + '-'))
}

function num (v) {
  const n = Number(v)
  return Number.isFinite(n) && n > 0 ? n : null
}

function truthy (v) {
  return v === '1' || v === 'true'
}

// Ids need matching in both directions. Current models are listed bare
// ("claude-opus-5") but a transcript may carry a dated variant; legacy models
// are listed dated ("claude-opus-4-5-20251101") and may be requested bare.
// Try exact, then longest table key that prefixes the id, then longest id that
// prefixes a table key. Longest wins so "claude-opus-4-5" cannot shadow a
// future "claude-opus-4-5-mini".
export function modelCeiling (model) {
  if (!model) return null
  // Ids may carry a [1m] suffix ("claude-opus-4-8[1m]") — the CLI's marker for
  // an explicitly selected 1M variant, stripped before the id reaches the
  // provider. Strip it here too so the table lookup sees the bare id.
  model = model.replace(/\[1m\]$/, '')
  if (MODEL_WINDOWS[model]) return MODEL_WINDOWS[model]
  let best = null
  let bestLen = 0
  for (const [id, size] of Object.entries(MODEL_WINDOWS)) {
    const prefix = model.startsWith(id) ? id : (id.startsWith(model) ? model : null)
    if (prefix && prefix.length > bestLen) {
      best = size
      bestLen = prefix.length
    }
  }
  return best
}

// These env vars are the CLI's private, undocumented surface. They were found
// by dumping a real hook process's environment, not from documentation, and can
// be renamed between versions — so every read is optional and falls through
// silently.
//
// `model` should be the ACTIVE model. The caller (guard.mjs) reads it from the
// transcript tail, which stamps every assistant message with the model that
// produced it — the only signal that survives a mid-session /model switch. The
// $ANTHROPIC_MODEL default here is the fallback for when no transcript is
// available: it is stamped at session start and goes stale the moment the user
// switches models (observed live: a fable-5 session whose hook environment
// still said claude-sonnet-4-6).
export function resolveWindow (configured, model = process.env.ANTHROPIC_MODEL) {
  // 1. Explicit config wins: someone who set a number knows their setup better
  //    than any inference here.
  const fromConfig = num(configured)
  if (fromConfig) return fromConfig

  // 2. A hard cap from the CLI or from settings.json `env`. Both reach the hook
  //    process — verified empirically.
  const cap = num(process.env.CLAUDE_CODE_MAX_CONTEXT_TOKENS)
  if (cap) return cap

  // 3. The auto-compact window, which is the figure /context displays.
  const autoCompact = num(process.env.CLAUDE_CODE_AUTO_COMPACT_WINDOW)
  if (autoCompact) return autoCompact

  // 4. The model's API ceiling, clamped only when a documented off-switch is
  //    active. Every table entry is >= BASE_TIER, so "clamp" means "return the
  //    base tier".
  const oneM = /\[1m\]$/.test(model ?? '')
  const ceiling = modelCeiling(model) ?? BASE_TIER

  // Documented off-switch, for deployments that need to cap context. Measured:
  // it drops a default 967k sonnet-5 session to 200k. Outranks everything
  // below, including an explicit [1m] variant — the flag removes 1M variants
  // from the model picker, so honoring a suffix past it would defeat the cap.
  if (truthy(process.env.CLAUDE_CODE_DISABLE_1M_CONTEXT)) return BASE_TIER

  // An explicit [1m] variant is a definitive 1M signal even for an id the
  // table has not caught up with, and per the docs it is exactly how a user
  // gets the full window behind a gateway — so it beats the gateway clamp.
  if (oneM) return Math.max(ceiling, 1_000_000)

  // Behind an LLM gateway Claude Code can't verify 1M support and budgets the
  // base tier; mirror that.
  const base = process.env.ANTHROPIC_BASE_URL
  if (base && !/^https?:\/\/api\.anthropic\.com\/?$/.test(base)) return BASE_TIER

  // The ceiling is what the model CAN address; the default is what a session
  // actually gets. Only models measured (or documented) as 1M-by-default
  // report their ceiling — a 1M-capable model whose 1M is opt-in runs at the
  // base tier unless the [1m] suffix said otherwise above.
  return defaultsToOneM(model) ? ceiling : BASE_TIER
}

// What is actually available before auto-compact fires — the number the user
// cares about. A nominal 200k window carries a 33k auto-compact reserve, so a
// skill's real cost is its share of 167k, not of the nominal figure. Matches
// /context measured 2026-08-10: 167k at 200k, 967k at 1M (sonnet-5's
// documented default compaction threshold).
export function usableBudget (window) {
  if (!window) return null
  // The max(0) guards a configured window smaller than the reserve itself.
  return Math.max(0, window - AUTOCOMPACT_RESERVE)
}
