// Effective context window and usable budget, resolved at hook time.
//
// No imports, no I/O, no network: this is on the hot path. It reads environment
// variables and consults a baked table. Nothing else.
//
// THE DISTINCTION THAT MATTERS. A model's API context window
// (max_input_tokens — 1M on every current frontier model) is NOT the window
// Claude Code gives its main loop. Measured 2026-08-05 via /context in a live
// session: model claude-opus-5, whose API window is 1M, reported
// "Auto-compact window: 200k tokens". Claude Code caps the main loop to the
// base tier unless the 1M context beta is active, and beta eligibility is an
// account property that no environment variable exposes.
//
// So MODEL_WINDOWS is a CEILING, not the answer. Reporting a skill as "6% of
// your 1000k window" when it is really 9% of a 200k window would be worse than
// the hardcoded 200000 it replaced. Resolution below goes: explicit config,
// then what the CLI tells us, then the model ceiling clamped to the base tier.
// It never guesses UP — same reason the estimator never under-counts.

// Claude Code's default main-loop window.
const BASE_TIER = 200_000

// Fraction of the window usable before auto-compact fires. Read off Claude
// Code's own /context on 2026-08-05: a 200k window reported a 33k auto-compact
// buffer, leaving 167k (61.3k used + 105.7k free). Version-observed, not
// documented — so CLAUDE_AUTOCOMPACT_PCT_OVERRIDE wins when it is present.
const USABLE_FRACTION = 0.835

// Per-model API context ceilings (max_input_tokens), generated by
// `node scripts/models.mjs` from GET /v1/models on 2026-08-05. Regenerate when
// models ship; do not hand-edit. Hand-writing this table from memory got three
// of twelve rows wrong — sonnet-4-5 is 1M not 200k, and two invented models
// were not in the list at all.
//
// A model absent here falls back to BASE_TIER, which is correct for every model
// at or above the base tier and only overstates for a model with a window
// smaller than 200k. None exist today.
export const MODEL_WINDOWS = {
  'claude-opus-5': 1_000_000,
  'claude-sonnet-5': 1_000_000,
  'claude-fable-5': 1_000_000,
  'claude-opus-4-8': 1_000_000,
  'claude-opus-4-7': 1_000_000,
  'claude-sonnet-4-6': 1_000_000,
  'claude-opus-4-6': 1_000_000,
  'claude-opus-4-5-20251101': 200_000,
  'claude-haiku-4-5-20251001': 200_000,
  'claude-sonnet-4-5-20250929': 1_000_000,
}

function num (v) {
  const n = Number(v)
  return Number.isFinite(n) && n > 0 ? n : null
}

function truthy (v) {
  return v === '1' || v === 'true'
}

// Ids need matching in both directions. Current models are listed bare
// ("claude-opus-5") but a transcript may carry a dated variant; legacy models
// are listed dated ("claude-opus-4-5-20251101") and may be requested bare.
// Try exact, then longest table key that prefixes the id, then longest id that
// prefixes a table key. Longest wins so "claude-opus-4-5" cannot shadow a
// future "claude-opus-4-5-mini".
export function modelCeiling (model) {
  if (!model) return null
  if (MODEL_WINDOWS[model]) return MODEL_WINDOWS[model]
  let best = null
  let bestLen = 0
  for (const [id, size] of Object.entries(MODEL_WINDOWS)) {
    const prefix = model.startsWith(id) ? id : (id.startsWith(model) ? model : null)
    if (prefix && prefix.length > bestLen) {
      best = size
      bestLen = prefix.length
    }
  }
  return best
}

// These env vars are the CLI's private, undocumented surface. They were found
// by dumping a real hook process's environment, not from documentation, and can
// be renamed between versions — so every read is optional and falls through
// silently.
//
// `model` defaults to $ANTHROPIC_MODEL, the CLI's own main-model override. It is
// unset in a normal session — the model is then whatever the user picked
// interactively, which reaches the hook nowhere — so this usually falls through
// to the base tier. It is wired up anyway because it costs nothing and is the
// only zero-I/O model signal available: learning the model for certain would
// mean parsing the transcript, which the hot path forbids.
export function resolveWindow (configured, model = process.env.ANTHROPIC_MODEL) {
  // 1. Explicit config wins: someone who set a number knows their setup better
  //    than any inference here.
  const fromConfig = num(configured)
  if (fromConfig) return fromConfig

  // 2. A hard cap from the CLI or from settings.json `env`. Both reach the hook
  //    process — verified empirically.
  const cap = num(process.env.CLAUDE_CODE_MAX_CONTEXT_TOKENS)
  if (cap) return cap

  // 3. The auto-compact window, which is the figure /context displays.
  const autoCompact = num(process.env.CLAUDE_CODE_AUTO_COMPACT_WINDOW)
  if (autoCompact) return autoCompact

  // 4. The model's API ceiling, clamped to the base tier. Unclamped this would
  //    report 1M for a session Claude Code is actually running at 200k. The
  //    clamp applies either way today; the explicit branch keeps the intent
  //    legible if the base tier ever moves.
  const ceiling = modelCeiling(model) ?? BASE_TIER
  if (truthy(process.env.CLAUDE_CODE_DISABLE_1M_CONTEXT)) return Math.min(ceiling, BASE_TIER)
  return Math.min(ceiling, BASE_TIER)
}

// What is actually available before auto-compact fires — the number the user
// cares about. A nominal 200k window with a 33k buffer and a reserved output
// budget leaves far less room than "200k" suggests, and a skill's real cost is
// its share of THAT, not of the nominal figure.
export function usableBudget (window) {
  if (!window) return null
  const pctOverride = num(process.env.CLAUDE_AUTOCOMPACT_PCT_OVERRIDE)
  const reservedOutput = num(process.env.CLAUDE_CODE_MAX_OUTPUT_TOKENS) || 0
  const ceiling = pctOverride ? window * (pctOverride / 100) : window * USABLE_FRACTION
  // A misconfigured setup can reserve more output than the ceiling allows;
  // clamp rather than report a negative budget.
  return Math.max(0, Math.round(ceiling - reservedOutput))
}
